### ISSUE TITLE
I am getting error of "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by devioand-aj** [stubbies/eu-vat-info#1]
<img width="1392" alt="Screenshot 2021-11-01 at 8 30 20 PM" src="https://user-images.githubusercontent.com/70755587/139697544-a88a271c-3708-4d98-9612-f187724c79df.png">
@stubbies

**Comment by stubbies** [comment]
@devioand released a new version with the fix **eu-vat-info@1.0.2**

**Comment by devioand-aj** [comment]
During function call, vatNumber accepts number type, but my number start from zero and JS removes the zero. So how I can pass that same number as it is
@stubbies

**Comment by stubbies** [comment]
> During function call, vatNumber accepts number type, but my number start from zero and JS removes the zero. So how I can pass that same number as it is @stubbies

Pushed the fix for this >  **eu-vat-info@1.0.3**
